### ISSUE TITLE
When is the release date for the cheat table for the free ones?

### ISSUE THREAD

**Issue by IshanChakrabortyYT** [xAranaktu/FIFA-23-CM-Cheat-Table#1]

**Comment by xAranaktu** [comment]
[Release Schedule For FIFA 23 Projects](https://docs.google.com/spreadsheets/d/1ucwqXILSAGVDREUgK8SMMzFqik-IRgkyMnSeCMYfMGs/edit#gid=1794541124)

**Comment by IshanChakrabortyYT** [comment]
> [Release Schedule For FIFA 23 Projects](https://docs.google.com/spreadsheets/d/1ucwqXILSAGVDREUgK8SMMzFqik-IRgkyMnSeCMYfMGs/edit#gid=1794541124)

It's saying the 22nd of October 2022 but I can't find it anywhere, I have checked here https://www.patreon.com/posts/fifa-23-cheat-1-73344192 it's showing locked.

Any idea when it will be unlocked? @xAranaktu

**Comment by xAranaktu** [comment]
8 PM CEST. For exact hours you need to join live editor discord server.
