### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by IshanChakrabortyYT** [xAranaktu/FIFA-23-CM-Cheat-Table#2]
First thing first really impressed by your work with Live editor and Cheat table @xAranaktu Keep up the good work really appreciate it.

### Feature Request
As I used your cheat table and I have a pretty good idea about the table, I have some ideas that you can add if you feel so please have a look when you feel.

- **Stadium editor:** As I played the game Fifa 23 I observed a few things like there are some important clubs, for example, FC Barcelona is having generic stadium and also there is the option from the game to edit the stadium from the main menu or in career mode. Sadly I checked that Fifa is not allowing me to add goal songs and entry songs for example for starting XI lineups, so thought of if you can have a look where if possible you can add them in the cheat table for upcoming versions it will be really great it's really sad that we can't add some goal songs or atmosphere improvements from game stadium editor.
- **Celebration editor:** I know it's there in the cheat table and also in the live editor but when I just copy the code from Messi and paste the finishing celebration id to any random forward player in my squad and in the match when I score a goal from that player and use the finishing celebration it celebrates randomly so can you have a look it's and [BUG] or not and also can you provide celebration ids and stadium ids?

If I missed something that you have already provided please share the link or details in the comments section.

Thanks please have a look and Keep doing your great work @xAranaktu.

**Comment by xAranaktu** [comment]
Maybe will be added one day, I don't know. At this moment I've different priorities.

**Comment by shektm** [comment]
When will the manual transfer players for the player career mode? regards!
