### ISSUE TITLE
Columns of Playernames.csv

### ISSUE THREAD

**Issue by justdan96** [xAranaktu/FIFA-23-CM-Cheat-Table#23]
For a script I am working on I needed to find the player names missing from this file:
https://github.com/xAranaktu/FIFA-23-CM-Cheat-Table/blob/main/other/playernames.csv

These names start from ID 44001 and continue up to 45654. I've managed to grab all of these names and their IDs but I don't know what the last column is in the CSV above so I'm not able to contribute these back. 

If you let me know I'll raise a PR and add them to the end of the CSV file.

**Comment by xAranaktu** [comment]
It's [commentaryid](https://github.com/xAranaktu/FIFA-23-CM-Cheat-Table/blob/3e85ce1df17edf74834f143038edeb393895e152/lua/imports/GameDBManager.lua#L32). Cheat table doesn't use it.

**Comment by justdan96** [comment]
Thank you, I've submitted https://github.com/xAranaktu/FIFA-23-CM-Cheat-Table/pull/24.
