### ISSUE TITLE
Morale and Form auto update/set value

### ISSUE THREAD

**Issue by Ammar7347** [xAranaktu/FIFA-23-CM-Cheat-Table#25]
I would like to suggest some changes to the Morale and Form options to be like Fitness and Sharpness. The Fitness and Sharpness options are one time toggle which makes sure that Fitness is auto restored or is 100% after a training session which means the players are always 100% Fit for my next match and Sharpness uses the set value so it never goes below 100. However, Morale and Form have to be toggled again and again after each match or before a match to get the desired result. 

I used to counter this minor annoyance/inconvenience by making  "hotkeys" assigned to my numpad so that I don't have to alt-tab out of the game to toggle. But I wanted to request for this enhancement and quality of life improvement if possible. I hope you figure out a way to make the Morale and Form to be closer to "one-time toggle".

**Comment by anwar125** [comment]
I uploaded a new exe version here:
shorturl.at/ikvN3

**Comment by Ammar7347** [comment]
Closing this because as per repository owner, they won't add any new feature in the Cheat Table.
