### ISSUE TITLE
Detected by EA Anti Cheat System 

### ISSUE THREAD

**Issue by ilker-binzet** [xAranaktu/FIFA-23-CM-Cheat-Table#3]
Hello,

I have a problem. Here's what the error says: This software cannot be used at the same time as the game. I added screenshot.

![Untitled Project](https://user-images.githubusercontent.com/19547599/200665356-439dafe9-d6a8-4486-811f-fc610644c602.png)

**Comment by xAranaktu** [comment]
You need to run the game without EA Anticheat and with Live Editor.
Read [Getting Started](https://github.com/xAranaktu/FIFA-23-CM-Cheat-Table/wiki/Getting-Started)
