### ISSUE TITLE
Feature Request: Perfect Timed Shots

### ISSUE THREAD

**Issue by Ammar7347** [xAranaktu/FIFA-23-CM-Cheat-Table#37]
Is it possible if you could maybe add perfect timed shots (timed shot mechanics) in the cheat table? Currently, the perfect/green timed shots are very accurate and most importantly very powerful and hit like a rocket and it would be great if you could hit the perfect timed shot every time. I realise that FIFA 23 is coming to its EOL but I hope if this doesn't get added in FIFA23 then maybe in the next EA Sports FC 24 perhaps?

**Comment by xAranaktu** [comment]
I've added this to the live editor in the last update ( v23.1.2.8). 
I don't plan to add any new features to the cheat table, so I don't think it will be ever added.
