### ISSUE TITLE
CaptainId`

### ISSUE THREAD

**Issue by DrExcalibur1** [xAranaktu/FIFA-23-CM-Cheat-Table#38]
How can I become captain in player career mode?

Every time I put the Leadership trait it dissapears after a game or when I leave. And even if I have it I am not captain. I searched for captainid in cheat engine and changed the id to my player id and still didn't worked.
![TTable](https://github.com/xAranaktu/FIFA-23-CM-Cheat-Table/assets/123599557/4ac9b4b1-5371-4f54-a0a6-e503dca1e683)

**Comment by xAranaktu** [comment]
You can't.
