### ISSUE TITLE
Do you have any records of how you managed to map the table's modifiable attributes?

### ISSUE THREAD

**Issue by noobandrew** [xAranaktu/FIFA-23-CM-Cheat-Table#57]
Do you have any records of how you managed to map the table's modifiable attributes? I want SO BAD to contribute by creating some user scripts for it but I need some reference material. Or to know if learning LUA is enough.

**Comment by xAranaktu** [comment]
What kind of reference material you need? You can find bunch of example lua scripts [here](https://github.com/xAranaktu/FIFA-23-CM-Cheat-Table/tree/main/users%20scripts). All of them are showing how to modify the database. If you don't know table names and field names then you can for example download RDBM and open your career file in it or extract `fifa_ng_db-meta.XML` from game legacy with FET or LE.

**Comment by noobandrew** [comment]
Thanks, guess that will work. :)
