### ISSUE TITLE
Stimulate All gets Freeze in Training

### ISSUE THREAD

**Issue by IshanChakrabortyYT** [xAranaktu/FIFA-23-CM-Cheat-Table#6]
When I Change my Team Sheet in Manager Carrer Mode in Training and then Stimulate All the game freezes.
@xAranaktu  Please look into this and fix this.

**Comment by IshanChakrabortyYT** [comment]
@xAranaktu Please check the issue.
Any update regarding this??

**Comment by EvilAsDevil** [comment]
i **was** going to get this cheat table only for the players training
