### ISSUE TITLE
Cheat table issue - (you are not in main menu. Enter there and close this window.

### ISSUE THREAD

**Issue by vundziak** [xAranaktu/FIFA-23-CM-Cheat-Table#60]
Hi, can you help me to solve this problem ? I literally try hunred times to fix that, and surprisingly, the cheat table works two times randomly, after some settings changes, computer restarts, but then it doesn't want to work, even if I repeat the same steps I did to make it work. (I tried newest version of cheat table, and older version 7.4, i turn off all anti-cheats, windows defender etc. , and nothing helps)

https://www.youtube.com/watch?v=h-T4pC3Lgmg

**Comment by xAranaktu** [comment]
Enter "Edit player" menu in-game and then start cheat engine and cheat table, or turn off FIFER's realism mod.
