### ISSUE TITLE
FUT clone not working (FIFA 21/22/23)

### ISSUE THREAD

**Issue by ReoN1993** [xAranaktu/FIFA-23-CM-Cheat-Table#7]
The table is wonderful beyond any doubt, but only one little thing upsets...

Cloning does not work with FUT (Usual career player cloning is a working). Logs write Futbin error: !DOCTYPE html. I think this problem started with FIFA 21 and 23 is no exception. And the most interesting thing is that this problem affected only a few. Can this problem be solved somehow?

For info **FUTbin** works for me...

**Comment by xAranaktu** [comment]
Won't be fixed anytime soon.
