### ISSUE TITLE
Player Stat Changes Reset

### ISSUE THREAD

**Issue by JediMindTrickk** [xAranaktu/FIFA-23-CM-Cheat-Table#8]
Hi there. Editing a player my My Career sets the stats only temporarily. They reset after a save, or when a new match starts. I understand this is a persisting issue from other versions. How to resolve in FIFA 23?

**Comment by xAranaktu** [comment]
It's not possible to edit attributes permanently in player career mode. The only way to improve your player in that mode is the [999 Skill Points](https://github.com/xAranaktu/FIFA-23-CM-Cheat-Table/wiki/999-Skill-Points) script

**Comment by JediMindTrickk** [comment]
Great, that's fine. Thank you!!!
