### ISSUE TITLE
Manager Mode national team offer not working

### ISSUE THREAD

**Issue by LennoxTF** [xAranaktu/FIFA-23-CM-Cheat-Table#9]
Hey,

I dont know if it´s me or a bug. But for the national team offer, I can´t enter anything for value in the main menu. Adress is just a bunch of ? there. It only works when I load a career but then, the offer doesn´t show up. Is it my fault?

**Comment by xAranaktu** [comment]
Read [that](https://github.com/xAranaktu/FIFA-23-CM-Cheat-Table/wiki/Manager-Job-Offer#job-from-any-national-team)
